### ISSUE TITLE
unitig-caller find unitigs from the file containing genes seq?

### ISSUE THREAD

**Issue by sekhwal** [johnlees/unitig-caller#12]
Hi,
I am looking to find Unitigs from the antimicrobial resistance genes generated from ResFinder. Please let me know if the pipeline works to predict Unitigs from the files containing antimicrobial resistance genes. I am planing to use the output file for making a machine learning model.
Thank you,

**Comment by johnlees** [comment]
Nothing fundamentally stopping this working I think, though the sequences might be smaller/more fragmented than from assemblies. I would just give it a go
