### ISSUE TITLE
Running into error when running simple mode

### ISSUE THREAD

**Issue by sapoudel** [johnlees/unitig-caller#18]
I am trying to use the simple mode to create a prediction output but running into this error.

```
$ unitig-caller --simple --refs inputfa_297.txt --unitigs queries.txt --out calls --threads 20
Constructing indexes for all input sequences...
Traceback (most recent call last):
  File "/home/spo/anaconda3/envs/kmerml/bin/unitig-caller", line 11, in <module>
    sys.exit(main())
  File "/home/spo/anaconda3/envs/kmerml/lib/python3.10/site-packages/unitig_caller/__main__.py", line 175, in main
    unitig_query.call(fasta_in,
RuntimeError: Failed to write 8 bytes to output stream! Wrote 0
```
My unitig-caller version in `unitig-caller 1.2.1`

**Comment by johnlees** [comment]
Not sure what this might be, sorry. Things to try:

- Update to v1.3.0
- Ensure the output directory is writable
- Try with a smaller/test input
- Use the bifrost build mode rather than simple mode

**Comment by sapoudel** [comment]
Thanks! All the other modes are working so I was able to finish up my analysis. I will leave it up to you to decide whether you want to close the issue.
