### ISSUE TITLE
Missing sequences in unitig-caller

### ISSUE THREAD

**Issue by apredeus** [johnlees/unitig-caller#2]
Hello John, 

I've noticed a very strange behaviour of unitig-caller while trying to debug some interesting results I found with pyseer. Below is a picture of significant unitigs that were either mapped using blastn (with low complexity filters off), or counted from the output of unitig-counter, or called with unitig-caller. The latter seems to be missing lots of calls. I have ~ 3100 genomes, and used "--simple" mode - perhaps this was the problem? 

![image](https://user-images.githubusercontent.com/7825825/78057737-1e066d80-737f-11ea-8ada-63bc208f14fc.png)

**Comment by johnlees** [comment]
Thanks for reporting this, and sorry that I haven't had a chance to look at it until now. This does look suspicious, there's a factor of two which makes me wonder whether the reverse complements are being missed.

Looking at the code history, this was only added in 36690514a81deb247342117e87ec436cc5843209, aka v1.0.1. I see that bioconda only has v1.0.0, which would explain this error. This is my fault for forgetting to update it! I will do that now. If you use the `--index` and `--call` mode it should work

**Comment by apredeus** [comment]
Ah, that makes sense, thank you! And thanks for fixing it. 

One more thing possibly worth looking at - unitig-counter seems to get few more isolates than blast does. The reason for it is "corner cases" when part of the unitig in question is in the very beginning or end of the contig. Especially makes a difference for longer unitigs with lower allele frequency.
