### ISSUE TITLE
Fresh conda install throws error (fixed by using older bifrost version)

### ISSUE THREAD

**Issue by benrhodes26** [johnlees/unitig-caller#20]
If I create a fresh conda environment and then run `conda install -c bioconda unitig-caller`, followed by `unitig-caller --help`, I get the following error mesage:
```
Traceback (most recent call last):
  File "/home/ben/mambaforge/envs/pyseer_env_test/bin/unitig-caller", line 7, in <module>
    from unitig_caller.__main__ import main
  File "/home/ben/mambaforge/envs/pyseer_env_test/lib/python3.10/site-packages/unitig_caller/__main__.py", line 11, in <module>
    import unitig_query
ImportError: /home/ben/mambaforge/envs/pyseer_env_test/lib/python3.10/site-packages/unitig_query.cpython-310-x86_64-linux-gnu.so: undefined symbol: _ZN10GFA_Parser9open_readEv
```

When debugging, I noticed that bifrost is now at version 1.2.0. I found that pinning the bifrost version to 1.0.6 fixes the above error.

**Comment by johnlees** [comment]
Ah good, another package broken despite no code changes 🥲

Thanks for the bifrost pinning tip, I'll see if I can update the bioconda build

**Comment by johnlees** [comment]
Looks like by updating the build with new bifrost I've been able to fix this https://github.com/bioconda/bioconda-recipes/pull/40099

Hopefully that should be added to bioconda shortly
