### ISSUE TITLE
Error when running --call

### ISSUE THREAD

**Issue by vealvarez** [johnlees/unitig-caller#28]
Hello everyone!

I am getting this error when trying to run --call:

![image](https://github.com/bacpop/unitig-caller/assets/45977740/9e673124-0145-4843-95d4-26e8d3244081)

Could you please help me?

Thanks

**Comment by johnlees** [comment]
How have you installed unitig-caller, and what versions of bifrost do you have installed? If you could provide the output of `conda list` or similar, that would be very helpful.

Also if possible please post output as text rather than a screenshot (you can enclose in triple backticks ``` to format correctly) -- this makes it easier for us to search using the error messages!

**Comment by vealvarez** [comment]
I have installed unitig-caller with conda: conda install unitig-caller

I haven't installed bifrost. How do I install it?

This is conda list:

# packages in environment at /home/vero/Documentos/Programas/mambaforge:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                       2_gnu    conda-forge
bifrost                   1.3.1                h43eeafb_0    bioconda
boltons                   23.0.0             pyhd8ed1ab_0    conda-forge
brotli-python             1.1.0           py310hc6cd4ac_0    conda-forge
bzip2                     1.0.8                h7f98852_4    conda-forge
c-ares                    1.19.1               hd590300_0    conda-forge
ca-certificates           2023.11.17           hbcca054_0    conda-forge
certifi                   2023.11.17         pyhd8ed1ab_0    conda-forge
cffi                      1.15.1          py310h255011f_3    conda-forge
charset-normalizer        3.2.0              pyhd8ed1ab_0    conda-forge
colorama                  0.4.6              pyhd8ed1ab_0    conda-forge
conda                     23.3.1          py310hff52083_0    conda-forge
conda-libmamba-solver     23.3.0             pyhd8ed1ab_0    conda-forge
conda-package-handling    2.2.0              pyh38be061_0    conda-forge
conda-package-streaming   0.9.0              pyhd8ed1ab_0    conda-forge
cryptography              41.0.3          py310h75e40e8_0    conda-forge
fmt                       9.1.0                h924138e_0    conda-forge
icu                       73.2                 h59595ed_0    conda-forge
idna                      3.4                pyhd8ed1ab_0    conda-forge
jsonpatch                 1.32               pyhd8ed1ab_0    conda-forge
jsonpointer               2.0                        py_0    conda-forge
keyutils                  1.6.1                h166bdaf_0    conda-forge
krb5                      1.21.2               h659d440_0    conda-forge
ld_impl_linux-64          2.40                 h41732ed_0    conda-forge
libarchive                3.6.2                h039dbb9_1    conda-forge
libcurl                   8.2.1                hca28451_0    conda-forge
libedit                   3.1.20191231         he28a2e2_2    conda-forge
libev                     4.33                 h516909a_1    conda-forge
libffi                    3.4.2                h7f98852_5    conda-forge
libgcc-ng                 13.1.0               he5830b7_0    conda-forge
libgomp                   13.1.0               he5830b7_0    conda-forge
libiconv                  1.17                 h166bdaf_0    conda-forge
libmamba                  1.4.2                hcea66bb_0    conda-forge
libmambapy                1.4.2           py310h1428755_0    conda-forge
libnghttp2                1.52.0               h61bc06f_0    conda-forge
libnsl                    2.0.0                h7f98852_0    conda-forge
libsolv                   0.7.24               hfc55251_3    conda-forge
libsqlite                 3.43.0               h2797004_0    conda-forge
libssh2                   1.11.0               h0841786_0    conda-forge
libstdcxx-ng              13.1.0               hfd8a6a1_0    conda-forge
libuuid                   2.38.1               h0b41bf4_0    conda-forge
libxml2                   2.11.5               h232c23b_1    conda-forge
libzlib                   1.2.13               hd590300_5    conda-forge
lz4-c                     1.9.4                hcb278e6_0    conda-forge
lzo                       2.10              h516909a_1000    conda-forge
mamba                     1.4.2           py310h51d5547_0    conda-forge
ncurses                   6.4                  hcb278e6_0    conda-forge
openssl                   3.2.0                hd590300_1    conda-forge
packaging                 23.1               pyhd8ed1ab_0    conda-forge
pip                       23.2.1             pyhd8ed1ab_0    conda-forge
pluggy                    1.3.0              pyhd8ed1ab_0    conda-forge
pthread-stubs             0.4               h36c2ea0_1001    conda-forge
pybind11-abi              4                    hd8ed1ab_3    conda-forge
pycosat                   0.6.4           py310h5764c6d_1    conda-forge
pycparser                 2.21               pyhd8ed1ab_0    conda-forge
pyopenssl                 23.2.0             pyhd8ed1ab_1    conda-forge
pysocks                   1.7.1              pyha2e5f31_6    conda-forge
python                    3.10.12         hd12c33a_0_cpython    conda-forge
python_abi                3.10                    3_cp310    conda-forge
readline                  8.2                  h8228510_1    conda-forge
reproc                    14.2.4               h0b41bf4_0    conda-forge
reproc-cpp                14.2.4               hcb278e6_0    conda-forge
requests                  2.31.0             pyhd8ed1ab_0    conda-forge
ruamel.yaml               0.17.32         py310h2372a71_0    conda-forge
ruamel.yaml.clib          0.2.7           py310h1fa729e_1    conda-forge
setuptools                68.1.2             pyhd8ed1ab_0    conda-forge
tk                        8.6.12               h27826a3_0    conda-forge
toolz                     0.12.0             pyhd8ed1ab_0    conda-forge
tqdm                      4.66.1             pyhd8ed1ab_0    conda-forge
tzdata                    2023c                h71feb2d_0    conda-forge
unitig-caller             1.3.0           py310ha320341_2    bioconda
urllib3                   2.0.4              pyhd8ed1ab_0    conda-forge
wheel                     0.41.2             pyhd8ed1ab_0    conda-forge
xz                        5.2.6                h166bdaf_0    conda-forge
yaml-cpp                  0.7.0                h27087fc_2    conda-forge
zlib                      1.2.13               hd590300_5    conda-forge
zstandard                 0.19.0          py

**Comment by johnlees** [comment]
Great, thanks. Could you also please paste as text the original error message you got?

@samhorsfield96 any known incompatibility issue w/ bifrost 1.3.1 and unitig-caller? I can see that 1.3.1 was released a couple of months ago. Might just be that we need a rebuild with the new library.

Function missing is `BlockedBloomFilter::ReadBloomFilter(_IO_FILE*)`

**Comment by johnlees** [comment]
I don't see anything in the release notes about that function changing, but seems like 1.3.0 isn't backwards compatible with older .bfi files

**Comment by vealvarez** [comment]
> Great, thanks. Could you also please paste as text the original error message you got?
> 
> @samhorsfield96 any known incompatibility issue w/ bifrost 1.3.1 and unitig-caller? I can see that 1.3.1 was released a couple of months ago. Might just be that we need a rebuild with the new library

```
Traceback (most recent call last):
  File "/home/vero/Documentos/Programas/mambaforge/bin/unitig-caller", line 7, in <module>
    from unitig_caller.__main__ import main
  File "/home/vero/Documentos/Programas/mambaforge/lib/python3.10/site-packages/unitig_caller/__main__.py", line 11, in <module>
    import unitig_query
ImportError: /home/vero/Documentos/Programas/mambaforge/lib/python3.10/site-packages/unitig_query.cpython-310-x86_64-linux-gnu.so: undefined symbol: _ZN18BlockedBloomFilter15ReadBloomFilterEP8_IO_FILE

**Comment by johnlees** [comment]
Doing a rebuild here: https://github.com/bioconda/bioconda-recipes/pull/45035

**Comment by vealvarez** [comment]
Thanks!
Will this version be available through bioconda?

**Comment by johnlees** [comment]
Yes, when it's merged I can give you instructions on how to update.

For now, I think if you reinstall and downgrade bifrost with `conda install bifrost==1.2.0` it should work

**Comment by vealvarez** [comment]
Ok, I prefer to wait for instructions on how to update unitig-caller

**Comment by johnlees** [comment]
The fixed version is now on conda. Try reinstalling, it would be easiest if you used the same command to make a new environment entirely. Make sure you have build 3, you'll see the line `unitig-caller 1.3.0 py310ha320341_3 bioconda` in your `conda list` if this was resolved correctly (above you have build 2)
