### ISSUE TITLE
Too much memory usage?

### ISSUE THREAD

**Issue by GaloGS** [johnlees/unitig-caller#31]
Hi, I am trying to run unitig-caller in a HPC to be used in a GWAS with pyseer. 
Every time I try to use it the process is killed since the it runs out of memory. I have tried with up to 512GB RAM, and with k-mer lenghts 31, 25 and 21. 

I am calling unitigs in 1540 bacterial genomes, from fastq files with around 5 million reads per genome (2.5 million forward + 2.5 reverse).

I was wondering if it is normal that the process needs so much memory or if I may be doing something wrong.

Thank you very much.

**Comment by johnlees** [comment]
I would suggest using assemblies rather than reads as input. If they are public genomes, the assemblies might already be available through the allthebacteria or logan projects.

**Comment by GaloGS** [comment]
Thank you for the answer.

The assemblies are for sure not not available, we just sequenced them, and in any case I believe that using assemblies will defeat the purpose of using k-mers for GWAS instead of variants. I tried with 2TB of RAM and still did not work, so I will use another alternative for counting k-mers.

Thank you for your support,
Galo

**Comment by johnlees** [comment]
> I believe that using assemblies will defeat the purpose of using k-mers for GWAS instead of variants.

FWIW I don't think that's true. Assembling reads into unitigs preserves all the k-mers, assembling them into contigs can lose some but it's usually somewhat minimal.

But if you definitely want unitigs from reads, I think I would recommend cuttlefish as an alternative tool
